### PR TITLE
Remove legacy versions

### PR DESCRIPTION
**Pull request by KaspianDev**
[Let them die in peace.](https://howoldisminecraft1122.today/)

This commit also cleans up page a lot.

### CODE REVIEW

**Comment by LEOcab** [comment]
nonononono

KEEP ALL LEGACY VERSION PLS

dis whole commit: 0/10

**Comment by ghost** [comment]
Let them die.

**Comment by KaspianDev** [comment]
@retrooper merge

**Comment by retrooper** [comment]
Stop

**Comment by retrooper** [comment]
Let the holy old versions live.

**Comment by KaspianDev** [comment]
u rly want 2 be canceled sir

**Comment by DeadSpark** [comment]
keep em

**Comment by KaspianDev** [comment]
another person to cancel

**Comment by retrooper** [comment]
Why didn't you make a new PR for your change.

**Comment by ghost** [comment]
merge

**Review by ghost — APPROVED** [review]
GREAT CHANGE!!

**Comment by retrooper** [comment]
Dude can you stop

**Comment by KaspianDev** [comment]
cringe

**Pull request closed without merging**
